Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import matplotlib.pyplot as plt
import numpy as np

# Laden der Bilddateie als Numpy.array
image = plt.imread('bilder/Weissabgleich.jpg')

# Auslesen der Farbwerte eines Referenzpixels
x = 3900
y = 1300
ref_pixel = image[y,x]

# Berechnung der Skalierungsfaktoren und Normierung anhand des grÃ¼nen Farbkanals
rgb_scale = ref_pixel/ref_pixel[1]

# WeiÃŸabgleich des gesamten Bildes anhand der Skallierungsfaktoren
image_wb = (image/rgb_scale).astype('uint8')

# Darstellen des korrigierten Bildes
fig = plt.figure(figsize=(10,10))
plt.scatter(x,y, color='red', label="Referenzpixel")
plt.imshow(image_wb)
plt.legend(loc='best')
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[1], line 6[0m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      5[0m [38;5;66;03m# Laden der Bilddateie als Numpy.array[39;00m
[0;32m----> 6[0m image [38;5;241m=[39m [43mplt[49m[38;5;241;43m.[39;49m[43mimread[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mbilder/Weissabgleich.jpg[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      8[0m [38;5;66;03m# Auslesen der Farbwerte eines Referenzpixels[39;00m
[1;32m      9[0m x [38;5;241m=[39m [38;5;241m3900[39m

File [0;32m/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/matplotlib/pyplot.py:2597[0m, in [0;36mimread[0;34m(fname, format)[0m
[1;32m   2593[0m [38;5;129m@_copy_docstring_and_deprecators[39m(matplotlib[38;5;241m.[39mimage[38;5;241m.[39mimread)
[1;32m   2594[0m [38;5;28;01mdef[39;00m [38;5;21mimread[39m(
[1;32m   2595[0m         fname: [38;5;28mstr[39m [38;5;241m|[39m pathlib[38;5;241m.[39mPath [38;5;241m|[39m BinaryIO, [38;5;28mformat[39m: [38;5;28mstr[39m [38;5;241m|[39m [38;5;28;01mNone[39;00m [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m   2596[0m ) [38;5;241m-[39m[38;5;241m>[39m np[38;5;241m.[39mndarray:
[0;32m-> 2597[0m     [38;5;28;01mreturn[39;00m [43mmatplotlib[49m[38;5;241;43m.[39;49m[43mimage[49m[38;5;241;43m.[39;49m[43mimread[49m[43m([49m[43mfname[49m[43m,[49m[43m [49m[38;5;28;43mformat[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/matplotlib/image.py:1544[0m, in [0;36mimread[0;34m(fname, format)[0m
[1;32m   1537[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(fname, [38;5;28mstr[39m) [38;5;129;01mand[39;00m [38;5;28mlen[39m(parse[38;5;241m.[39murlparse(fname)[38;5;241m.[39mscheme) [38;5;241m>[39m [38;5;241m1[39m:
[1;32m   1538[0m     [38;5;66;03m# Pillow doesn't handle URLs directly.[39;00m
[1;32m   1539[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m   1540[0m         [38;5;124m"[39m[38;5;124mPlease open the URL for reading and pass the [39m[38;5;124m"[39m
[1;32m   1541[0m         [38;5;124m"[39m[38;5;124mresult to Pillow, e.g. with [39m[38;5;124m"[39m
[1;32m   1542[0m         [38;5;124m"[39m[38;5;124m``np.array(PIL.Image.open(urllib.request.urlopen(url)))``.[39m[38;5;124m"[39m
[1;32m   1543[0m         )
[0;32m-> 1544[0m [38;5;28;01mwith[39;00m [43mimg_open[49m[43m([49m[43mfname[49m[43m)[49m [38;5;28;01mas[39;00m image:
[1;32m   1545[0m     [38;5;28;01mreturn[39;00m (_pil_png_to_float_array(image)
[1;32m   1546[0m             [38;5;28;01mif[39;00m [38;5;28misinstance[39m(image, PIL[38;5;241m.[39mPngImagePlugin[38;5;241m.[39mPngImageFile) [38;5;28;01melse[39;00m
[1;32m   1547[0m             pil_to_array(image))

File [0;32m/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/PIL/Image.py:3469[0m, in [0;36mopen[0;34m(fp, mode, formats)[0m
[1;32m   3466[0m     filename [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mrealpath(os[38;5;241m.[39mfspath(fp))
[1;32m   3468[0m [38;5;28;01mif[39;00m filename:
[0;32m-> 3469[0m     fp [38;5;241m=[39m [43mbuiltins[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m   3470[0m     exclusive_fp [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m   3471[0m [38;5;28;01melse[39;00m:

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/home/runner/work/LectureComputerScience/LectureComputerScience/book/content/Exercises/03_datenanalyse/zusatzaufgaben/bilder/Weissabgleich.jpg'

