Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Hier wird der nachfolgende Datensatz kÃ¼nstlich generiert. Die genutzte 
# Methode kommt aus dem Modul sklearn.datasets, siehe
# https://scikit-learn.org/stable/modules/classes.html#module-sklearn.datasets
# Durch die Festlegung der Zufallszahlfolge, mittels des Arguments
# random_state, wir so bei jedem Durchlauf der gleiche Datensatz generiert

import sklearn.datasets
x, c = sklearn.datasets.make_blobs(random_state=144)

plt.scatter(x[:,0], x[:,1], color='grey')

plt.xlim([-10,10])
plt.ylim([-10,10])
plt.xlabel("A")
plt.ylabel("B");
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 7[0m
[1;32m      1[0m [38;5;66;03m# Hier wird der nachfolgende Datensatz kÃ¼nstlich generiert. Die genutzte [39;00m
[1;32m      2[0m [38;5;66;03m# Methode kommt aus dem Modul sklearn.datasets, siehe[39;00m
[1;32m      3[0m [38;5;66;03m# https://scikit-learn.org/stable/modules/classes.html#module-sklearn.datasets[39;00m
[1;32m      4[0m [38;5;66;03m# Durch die Festlegung der Zufallszahlfolge, mittels des Arguments[39;00m
[1;32m      5[0m [38;5;66;03m# random_state, wir so bei jedem Durchlauf der gleiche Datensatz generiert[39;00m
[0;32m----> 7[0m [38;5;28;01mimport[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdatasets[39;00m
[1;32m      8[0m x, c [38;5;241m=[39m sklearn[38;5;241m.[39mdatasets[38;5;241m.[39mmake_blobs(random_state[38;5;241m=[39m[38;5;241m144[39m)
[1;32m     10[0m plt[38;5;241m.[39mscatter(x[:,[38;5;241m0[39m], x[:,[38;5;241m1[39m], color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mgrey[39m[38;5;124m'[39m)

[0;31mModuleNotFoundError[0m: No module named 'sklearn'

